# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Ensure executable permissions
RUN chmod +x bin/cli.js

# Default command (will be overridden by MCP startCommand)
CMD ["node", "bin/cli.js"]
